export interface CommitmentItem {
  id: string;
  levelId: "nce" | "gad" | "gam" | "conjunto";
  levelName: string;
  commitment: string;
  deliverable: string;
  responsible: string;
  status: string;
  deadlineDate?: string;
  category?: string;
}

export interface CommitmentLevel {
  id: "nce" | "gad" | "gam" | "conjunto";
  name: string;
  shortName: string;
  badge: string;
  description: string;
  iconName: string;
  colorScheme: "blue" | "emerald" | "amber" | "purple";
  count: number;
}

export const commitmentLevels: CommitmentLevel[] = [
  {
    id: "nce",
    name: "Presidente / Gobierno Nacional (NCE)",
    shortName: "Nivel Central (NCE)",
    badge: "Ejecutivo Nacional",
    description: "Compromisos normativos, fiscales y técnicos de competencia del Órgano Ejecutivo y ministerios.",
    iconName: "Landmark",
    colorScheme: "blue",
    count: 18,
  },
  {
    id: "gad",
    name: "Gobiernos Autónomos Departamentales (GAD)",
    shortName: "Gobernaciones (GAD)",
    badge: "9 Departamentos",
    description: "Entregables técnicos, propuestas tributarias y estudios fiscales de las gobernaciones.",
    iconName: "Building2",
    colorScheme: "emerald",
    count: 15,
  },
  {
    id: "gam",
    name: "GAM (9 capitales + El Alto) — AMB",
    shortName: "Municipios (GAM - AMB)",
    badge: "10 Ciudades Principales",
    description: "Diagnósticos operativos, propuestas de alivio y reformas articuladas por la Asociación de Municipalidades.",
    iconName: "Building",
    colorScheme: "amber",
    count: 25,
  },
  {
    id: "conjunto",
    name: "Compromisos Conjuntos",
    shortName: "Acuerdos Conjuntos",
    badge: "Articulación Multinivel",
    description: "Instancias técnicas compartidas entre NCE, GAD y GAM para el Gran Acuerdo Nacional.",
    iconName: "Layers",
    colorScheme: "purple",
    count: 5,
  },
];

export const commitmentsData: CommitmentItem[] = [
  // 1. PRESIDENTE / GOBIERNO NACIONAL (NCE)
  {
    id: "nce-1",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "FPIEEH",
    deliverable: "Informe técnico sobre viabilidad de suspender, devolver o aplicar progresivamente el 12% del FPIEEH a los GAM",
    responsible: "Min. Hidrocarburos + MEFP",
    status: "14/10/2026",
    deadlineDate: "2026-10-14",
    category: "Hidrocarburos",
  },
  {
    id: "nce-2",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Ley 154",
    deliverable: "Proyecto de Ley que permita a los GAD crear y modificar impuestos propios",
    responsible: "MEFP",
    status: "03/11/2026",
    deadlineDate: "2026-11-03",
    category: "Tributario",
  },
  {
    id: "nce-3",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Información fiscal",
    deliverable: "Reportes periódicos de transferencias, ejecución presupuestaria y techos fiscales para que los GAD y GAM planifiquen",
    responsible: "MEFP",
    status: "Continuo",
    category: "Fiscal",
  },
  {
    id: "nce-4",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Cronograma de encuentros",
    deliverable: "Calendario público de reuniones del Presidente con municipios, IOC y Chaco",
    responsible: "Min. Presidencia / SEA",
    status: "Sin plazo",
    category: "Institucional",
  },
  {
    id: "nce-5",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Reporte único",
    deliverable: "Norma que elimine la obligación de pedir autorización previa al NCE para que los GAM ejecuten su presupuesto; se reemplaza por reporte de información",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Normativo",
  },
  {
    id: "nce-6",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Ley APP",
    deliverable: "Proyecto de Ley que permita a GAD y GAM asociarse con empresas privadas para obras públicas",
    responsible: "MEFP / Min. Planificación",
    status: "Sin plazo",
    category: "Inversión",
  },
  {
    id: "nce-7",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Ley 699",
    deliverable: "Proyecto de Ley que reemplace la Ley 699 para que las ETAs puedan acceder a cooperación internacional y financiamiento externo sin tanta burocracia",
    responsible: "Cancillería / SEA",
    status: "Sin plazo",
    category: "Internacional",
  },
  {
    id: "nce-8",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Ley 1178",
    deliverable: "Propuesta para simplificar los procedimientos administrativos y reducir la burocracia que frena la inversión pública municipal",
    responsible: "MEFP / Contraloría",
    status: "Sin plazo",
    category: "Administrativo",
  },
  {
    id: "nce-9",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Auditoría coparticipación",
    deliverable: "Informe de auditoría que muestre si los recursos de coparticipación tributaria transferidos a los GAM en los últimos años corresponden a lo que establece la ley",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Auditoría",
  },
  {
    id: "nce-10",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Distribución fiscal",
    deliverable: "Estudio con nueva fórmula que considere población, capacidad fiscal, esfuerzo recaudatorio, NBI, IDH y costos reales de servicios urbanos",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Fiscal",
  },
  {
    id: "nce-11",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Financiamiento modular",
    deliverable: "Propuesta de instrumentos financieros optativos para que cada GAM acceda según su perfil crediticio",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Financiero",
  },
  {
    id: "nce-12",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "PRFT",
    deliverable: "Reglamento y esquema de reprogramación de deudas y saneamiento fiscal para GAD y GAM",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Deuda",
  },
  {
    id: "nce-13",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Normativa que condiciona gasto GAD",
    deliverable: "Informe que identifique todas las leyes nacionales que obligan a los GAD a gastar en cosas que no les corresponden",
    responsible: "SEA / Min. Presidencia",
    status: "Sin plazo",
    category: "Competencial",
  },
  {
    id: "nce-14",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Derogar condicionalidades",
    deliverable: "Norma que elimine las obligaciones de gasto que financian competencias del nivel central o instituciones que ya no existen",
    responsible: "NCE",
    status: "Sin plazo",
    category: "Normativo",
  },
  {
    id: "nce-15",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "LMAD",
    deliverable: "Anteproyecto de Ley de modificación de la Ley Marco de Autonomías para fortalecer el régimen autonómico",
    responsible: "Viceministerio de Autonomías",
    status: "Sin plazo",
    category: "Autonomías",
  },
  {
    id: "nce-16",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Fondos de compensación",
    deliverable: "Estudio para crear fondos que compensen a los departamentos con menos recursos",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Solidaridad",
  },
  {
    id: "nce-17",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Transferencia de instituciones",
    deliverable: "Diagnóstico sobre qué instituciones públicas podrían pasar a administración de los GAD",
    responsible: "NCE",
    status: "Sin plazo",
    category: "Institucional",
  },
  {
    id: "nce-18",
    levelId: "nce",
    levelName: "Presidente / Gobierno Nacional (NCE)",
    commitment: "Cronograma alivio fiscal GAD",
    deliverable: "Calendario de medidas de alivio financiero para los gobiernos departamentales",
    responsible: "MEFP",
    status: "Sin plazo",
    category: "Alivio Fiscal",
  },

  // 2. GOBIERNOS AUTÓNOMOS DEPARTAMENTALES (GAD)
  {
    id: "gad-1",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Propuestas tributarias",
    deliverable: "Documento con propuestas de cada GAD para ampliar sus ingresos propios",
    responsible: "Cada GAD",
    status: "Cumplido (4 GAD)",
    category: "Tributario",
  },
  {
    id: "gad-2",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Información al SEA",
    deliverable: "Datos económicos y fiscales de cada departamento para la nueva distribución de ingresos",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Información",
  },
  {
    id: "gad-3",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Ley 154",
    deliverable: "Proyecto de Ley que permita a los departamentos crear o modificar impuestos propios",
    responsible: "Cada GAD + MEFP",
    status: "03/11/2026",
    deadlineDate: "2026-11-03",
    category: "Tributario",
  },
  {
    id: "gad-4",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Estudios tributarios",
    deliverable: "Informes sobre: ampliar dominio tributario, crear sobretasas, aplicar impuesto ambiental, reclasificar al menos una base imponible del nivel central",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Tributario",
  },
  {
    id: "gad-5",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Revisar condicionalidades",
    deliverable: "Informe que identifique todas las normas nacionales que obligan a los GAD a gastar en cosas ajenas a sus competencias",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Competencial",
  },
  {
    id: "gad-6",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Relación presupuestaria",
    deliverable: "Estudio para que el NCE solo controle los agregados fiscales y los GAD decidan su presupuesto",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Presupuesto",
  },
  {
    id: "gad-7",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Transferencias fiscales",
    deliverable: "Estudio para adecuar las transferencias del NCE a las competencias reales de cada GAD",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Transferencias",
  },
  {
    id: "gad-8",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Mesa Ley Coparticipación",
    deliverable: "Instalación de mesa técnica para elaborar el Proyecto de Ley Especial de Coparticipación y Distribución de Recursos Fiscales",
    responsible: "GAD + NCE",
    status: "Sin plazo",
    category: "Mesas Técnicas",
  },
  {
    id: "gad-9",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Cronograma alivio fiscal",
    deliverable: "Calendario de medidas de reprogramación y diferimiento de deudas de cada GAD",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Deuda",
  },
  {
    id: "gad-10",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Propuestas compensación",
    deliverable: "Documento con propuestas de cada GAD sobre fondos de compensación y transferencia de instituciones",
    responsible: "Cada GAD",
    status: "Sin plazo",
    category: "Compensación",
  },
  {
    id: "gad-11",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "LMAD",
    deliverable: "Propuesta de modificación de la Ley Marco de Autonomías",
    responsible: "GAD + NCE",
    status: "Sin plazo",
    category: "Normativo",
  },
  {
    id: "gad-12",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Ley APP",
    deliverable: "Propuesta de normativa que permita a los GAD asociarse con privados para obras públicas",
    responsible: "GAD + NCE",
    status: "Sin plazo",
    category: "Inversión",
  },
  {
    id: "gad-13",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Ley 699",
    deliverable: "Propuesta de nueva Ley de Relacionamiento Internacional",
    responsible: "GAD + NCE",
    status: "Sin plazo",
    category: "Internacional",
  },
  {
    id: "gad-14",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Fondos de compensación",
    deliverable: "Estudio para crear fondos que compensen a los departamentos con menos recursos",
    responsible: "GAD + NCE",
    status: "Sin plazo",
    category: "Solidaridad",
  },
  {
    id: "gad-15",
    levelId: "gad",
    levelName: "Gobiernos Autónomos Departamentales (GAD)",
    commitment: "Transferencia de instituciones",
    deliverable: "Diagnóstico sobre qué instituciones nacionales podrían pasar a los GAD",
    responsible: "GAD + NCE",
    status: "Sin plazo",
    category: "Institucional",
  },

  // 3. GAM (9 CAPITALES + EL ALTO) — ARTICULADOS POR LA AMB
  {
    id: "gam-1",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Salud",
    deliverable: "Plan municipal que asegure que los hospitales de primer y segundo nivel tengan infraestructura, equipamiento, medicamentos y financiamiento suficiente",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Salud",
  },
  {
    id: "gam-2",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Competencias y cargas",
    deliverable: "Diagnóstico que identifique qué competencias ejerce cada GAM que no le corresponden, cuánto le cuestan y qué duplicidades existen con el NCE",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Competencias",
  },
  {
    id: "gam-3",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Brechas operativas",
    deliverable: "Diagnóstico que cuantifique cuánto le falta a cada GAM para prestar bien servicios como seguridad ciudadana, educación, residuos, movilidad e infraestructura",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Servicios Urbanos",
  },
  {
    id: "gam-4",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Gobernanza metropolitana",
    deliverable: "Esquema de coordinación entre municipios conurbados para compartir infraestructura y servicios",
    responsible: "GAM conurbados",
    status: "Sin plazo",
    category: "Metropolitano",
  },
  {
    id: "gam-5",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Reporte único",
    deliverable: "Medida para que los GAM reporten información al NCE una sola vez, en un solo formato y por un solo canal",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Gestión",
  },
  {
    id: "gam-6",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Gobierno abierto",
    deliverable: "Plataforma digital con indicadores de transparencia, Centro de Datos Autonómicos y portal de seguimiento de la Agenda 50/50",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Transparencia",
  },
  {
    id: "gam-7",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Ley 1178",
    deliverable: "Propuesta para simplificar los procedimientos administrativos que frenan la inversión pública municipal",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Inversión",
  },
  {
    id: "gam-8",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Normativa restrictiva",
    deliverable: "Informe que identifique las leyes nacionales que limitan la autonomía municipal o condicionan su gasto",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Normativo",
  },
  {
    id: "gam-9",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Cartas Orgánicas",
    deliverable: "Medidas para agilizar la aprobación y vigencia de las Cartas Orgánicas Municipales",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Institucional",
  },
  {
    id: "gam-10",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Dominio tributario",
    deliverable: "Estudio sobre qué impuestos propios podría crear cada GAM según su capacidad administrativa",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Tributario",
  },
  {
    id: "gam-11",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Ley 699",
    deliverable: "Propuesta de nueva Ley de Relacionamiento Internacional",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Internacional",
  },
  {
    id: "gam-12",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Ley APP",
    deliverable: "Propuesta de normativa que permita a los GAM asociarse con privados para obras públicas",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Inversión",
  },
  {
    id: "gam-13",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Marco laboral",
    deliverable: "Propuesta de reforma del régimen laboral municipal para reducir conflictividad y contingencias",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Laboral",
  },
  {
    id: "gam-14",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Auditoría coparticipación",
    deliverable: "Auditoría que muestre si los recursos de coparticipación transferidos a los GAM corresponden a lo que establece la ley",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Auditoría",
  },
  {
    id: "gam-15",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Distribución fiscal",
    deliverable: "Estudio con nueva fórmula que considere población, capacidad fiscal, esfuerzo recaudatorio, NBI, IDH y costos reales de servicios urbanos",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Fiscal",
  },
  {
    id: "gam-16",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Financiamiento modular",
    deliverable: "Propuesta de instrumentos financieros optativos según el perfil crediticio de cada GAM",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Financiero",
  },
  {
    id: "gam-17",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "PRFT",
    deliverable: "Esquema de reprogramación de deudas y saneamiento fiscal para cada GAM",
    responsible: "Cada GAM",
    status: "Sin plazo",
    category: "Deuda",
  },
  {
    id: "gam-18",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "Análisis FPIEEH",
    deliverable: "Análisis interno de cada GAM sobre el impacto de la respuesta del Min. Hidrocarburos y MEFP",
    responsible: "Cada GAM",
    status: "14/10/2026",
    deadlineDate: "2026-10-14",
    category: "FPIEEH",
  },
  {
    id: "gam-19",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Diagnóstico conjunto",
    deliverable: "Documento único con el diagnóstico de los 10 GAM sobre la situación municipal",
    responsible: "AMB",
    status: "Cumplido",
    category: "Diagnóstico",
  },
  {
    id: "gam-20",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Metodología (Anexo a)",
    deliverable: "Documento con la propuesta metodológica de la Agenda 50/50 para municipios",
    responsible: "AMB",
    status: "Sin plazo",
    category: "Metodología",
  },
  {
    id: "gam-21",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Normativa priorizada (Anexo b)",
    deliverable: "Documento con la lista de normas que deben modificarse para fortalecer la autonomía municipal",
    responsible: "AMB",
    status: "Sin plazo",
    category: "Normativo",
  },
  {
    id: "gam-22",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Condicionalidad del gasto (Anexo c)",
    deliverable: "Documento con el análisis de las 25 condicionalidades que pesan sobre los GAM (9 rígidas y 16 flexibles)",
    responsible: "AMB",
    status: "Entregado",
    category: "Condicionalidades",
  },
  {
    id: "gam-23",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Matriz laboral (Anexo d)",
    deliverable: "Documento con la problemática del régimen laboral municipal y propuestas de reforma",
    responsible: "AMB",
    status: "Sin plazo",
    category: "Laboral",
  },
  {
    id: "gam-24",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Sistematización GAD",
    deliverable: "Documento que ordena las propuestas que enviaron los GAD al SEA",
    responsible: "AMB",
    status: "En curso",
    category: "Articulación",
  },
  {
    id: "gam-25",
    levelId: "gam",
    levelName: "GAM (9 capitales + El Alto) — AMB",
    commitment: "AMB – Socialización PRFT",
    deliverable: "Jornadas de socialización del reglamento del PRFT entre los 10 GAM",
    responsible: "AMB",
    status: "Sin plazo",
    category: "Socialización",
  },

  // 4. COMPROMISOS CONJUNTOS
  {
    id: "con-1",
    levelId: "conjunto",
    levelName: "Compromisos conjuntos",
    commitment: "Mesas técnicas",
    deliverable: "Reuniones permanentes de trabajo entre NCE, GAD y GAM para los 3 ejes de la Agenda",
    responsible: "NCE + GAD + GAM",
    status: "Permanente",
    category: "Articulación",
  },
  {
    id: "con-2",
    levelId: "conjunto",
    levelName: "Compromisos conjuntos",
    commitment: "Consejo de Coordinación Técnica",
    deliverable: "Convocatoria formal del Consejo que articulará el Gran Acuerdo Nacional",
    responsible: "NCE + GAD + GAM",
    status: "Convocatoria",
    category: "Institucional",
  },
  {
    id: "con-3",
    levelId: "conjunto",
    levelName: "Compromisos conjuntos",
    commitment: "Gran Acuerdo Nacional",
    deliverable: "Acuerdo final que integre los acuerdos 001 y 002 en un solo instrumento",
    responsible: "NCE + GAD + GAM",
    status: "En proceso",
    category: "Gran Acuerdo",
  },
  {
    id: "con-4",
    levelId: "conjunto",
    levelName: "Compromisos conjuntos",
    commitment: "Ley Especial de Coparticipación",
    deliverable: "Proyecto de Ley que reemplace el actual sistema de coparticipación tributaria",
    responsible: "NCE + GAD + GAM",
    status: "Gestión 2027",
    category: "Pacto Fiscal",
  },
  {
    id: "con-5",
    levelId: "conjunto",
    levelName: "Compromisos conjuntos",
    commitment: "Implementación PRFT",
    deliverable: "Puesta en marcha del Programa de Readecuación Financiera Territorial",
    responsible: "NCE + GAD + GAM",
    status: "Saneamiento",
    category: "Financiero",
  },
];
